return {
	"nvim-treesitter/nvim-treesitter",
	--    build = ":TSUpdate",
	config = function()
		local configs = require("nvim-treesitter.configs")

		configs.setup({
			ensure_installed = {
				"c",
				"lua",
				"vim",
				"vimdoc",
				"query",
				"elixir",
				"heex",
				"javascript",
				"html",
				"python",
				"java",
				"css",
				"bash",
				"regex",
				"json",
				"yaml",
				"typescript",
				"tsx",
				"rust",
				"ruby",
				"php",
				"jsonc",
				"scss",
				"toml",
				"cpp",
				"cmake",
				"dockerfile",
				"go",
				"haskell",
			},
			sync_install = false,
			highlight = { enable = true },
			indent = { enable = true },
			auto_install = true,
		})
	end,
}
